language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '12'
  - '14'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - npm run test -- --coverage
branches:
  only:
    - master
    - next
    - beta
    - /^\d+\.(\d+|x)(\.x)?$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
